SocialMediaCenter/Controllers/ArticleController.cs
using Common;
using SocialMediaCenter.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LogicLayer.Decorator;
using LogicLayer.AbstractFactory;
using LogicLayer.Models;
using LogicLayer;

namespace SocialMediaCenter.Controllers
{
    public class ArticleController : Controller
    {
        // GET: Article
        [Authorize(Roles = "Writer, MediaManager, Admin")]
        public ActionResult Index()
        {
            return View();
        }

        // GET: Article/Details/5
        [Authorize(Roles = "Writer, MediaManager, Admin")]
        public ActionResult Details(int articleId)
        {
            Model_ArticleDetails model = new Model_ArticleDetails();
            model.articleId = articleId;
            return View(model);
        }

        // GET: Article/Create
        [Authorize(Roles = "Writer, MediaManager")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Article/Create
        [HttpPost]
        public ActionResult Create(LogicLayer.Models.Model_ArticleCreate model)
        {
            try
            {
                Article newArticle;
                if (model.article_title == "")
                {
                    ArticleCreator notTitle = new ArticleCreator(new NoTitleArticleFactory(), model, User.Identity.Name);
                    newArticle = notTitle.getArticle();
                }
                else {
                    ArticleCreator plainArticle = new ArticleCreator(new PlainArticleFactory(), model, User.Identity.Name);
                    newArticle = plainArticle.getArticle();
                }
                
                
                new LogicLayer.ArticleRepository().createArticle(newArticle);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Article/Edit/5
        [Authorize(Roles = "Writer, MediaManager")]
        public ActionResult Edit(int articleId)
        {
            Model_ArticleUpdate model = new Model_ArticleUpdate();
            model.articleId = articleId;
            return View(model);
        }

        // POST: Article/Edit/5
        [HttpPost]
        public ActionResult Edit(Model_ArticleUpdate model)
        {
            try
            {
                Article a = new ArticleRepository().getArticle(model.articleId);
                model.author = a.author;
                model.state = a.state;
                model.workflow = a.workflow_id;
                new ArticleRepository().updateArticle(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "Writer, MediaManager")]
        public ActionResult Review(int articleId) {
            LogicLayer.Models.Model_ArticleReview model = new LogicLayer.Models.Model_ArticleReview();

            model.articleId = articleId;
            return View(model);
        }

        [HttpPost]
        public ActionResult Review(LogicLayer.Models.Model_ArticleReview model) {
            try
            {
                Comment c = new Comment();
                c.articleid = model.articleId;
                c.comment1 = model.comment;
                c.author = User.Identity.Name;

                new LogicLayer.ArticleRepository().Review(model.articleId, c, model.accepted);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Article/Delete/5
        [Authorize(Roles = "Writer, MediaManager")]
        public ActionResult Delete(int articleId)
        {
            Model_ArticleDelete model = new Model_ArticleDelete();
            model.articleId = articleId;

            return View(model);
        }

        // POST: Article/Delete/5
        [HttpPost]
        public ActionResult Delete(Model_ArticleDelete model)
        {
            try
            {
                if (model.confirm)
                {
                    new ArticleRepository().deleteArticle(model.articleId);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SocialMediaCenter/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LogicLayer;
using LogicLayer.Models;
using Common;

namespace SocialMediaCenter.Controllers
{
    public class CommentController : Controller
    {
        // GET: Comment
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Edit(int commentId) {

            Model_CommentEdit model = new Model_CommentEdit();

            model.commentId = commentId;

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Model_CommentEdit model) {
            
            try
            {
                Comment c = new Comment();
                c.comment1 = model.comment;
                new LogicLayer.CommentsRepository().updateComment(model.commentId, c);
                return RedirectToAction("Index", "Article");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int commentId)
        {

            Model_CommentDelete model = new Model_CommentDelete();

            model.commentId = commentId;

            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(Model_CommentDelete model)
        {

            try
            {
                if (model.confirm)
                {
                    new CommentsRepository().deleteComment(model.commentId);
                }
                return RedirectToAction("Index", "Article");
            }
            catch
            {
                return View();
            }
        }
    }
}

SocialMediaCenter/Views/Article/Create.cshtml
@model LogicLayer.Models.Model_ArticleCreate

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    IEnumerable<Common.Workflow> workflows = new LogicLayer.WorkflowRepository().getWorkflows();
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ArticleCreateModel</h4>
        <hr />

            WorkFlow <select id="WorkFlow" name="workflow">

                <option value=""></option>

            @{ 
                foreach (var w in workflows)
                {
                    <option value="@w.workflow_id">@w.workflow_name</option>
                }
            }
            </select>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.article_title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.article_title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.article_title, "", new { @class = "text-danger" })
            </div>
        </div>


        @*<div class="form-group">
            @Html.LabelFor(model => model.lincense, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lincense, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lincense, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.article_text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.article_text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.article_text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SocialMediaCenter/Views/Article/Delete.cshtml
@model LogicLayer.Models.Model_ArticleDelete

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Delete Confirmation:</h2>

<h3> Are you sure you want to delete this article ?</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <input type="hidden" name="articleId" value="@Model.articleId">

    <div class="form-group">
        @Html.LabelFor(model => model.confirm, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.RadioButtonFor(model => model.confirm, "true") Yes
            @Html.RadioButtonFor(model => model.confirm, "false") No
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Submit" class="btn btn-default" />
        </div>
    </div>

}

SocialMediaCenter/Views/Article/Details.cshtml
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    Common.Article articleInReview = new LogicLayer.ArticleRepository().getArticle(Model.articleId);
    IEnumerable<Common.Comment> allArticleComments = new LogicLayer.CommentsRepository().getCommentsForArticle(Model.articleId);
}

<h2>Viewing Article: </h2>

<h3> @articleInReview.article_title </h3>

<p> @articleInReview.article_text</p>

@Html.ActionLink("Edit", "Edit","Article", new { articleId = @articleInReview.articleid }, null) @Html.ActionLink("Delete", "Delete", new { articleId = @articleInReview.articleid }, null)

<h4> Comments: </h4>

<table>
    <tr>
        <td> Comment </td>
        <td>Author</td> </td>

        @{
            foreach (var c in allArticleComments)
            {
            <tr><td>@c.comment1</td> <td> @c.author</td> <td>@Html.ActionLink("Edit", "Edit","Comment", new { commentId = @c.commentid }, null)</td> <td>@Html.ActionLink("Delete", "Delete", "Comment", new { commentId = @c.commentid }, null)</td></tr>
            }
        }
     
</table>

SocialMediaCenter/Views/Article/Edit.cshtml
@model LogicLayer.Models.Model_ArticleUpdate
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    Common.Article article= new LogicLayer.ArticleRepository().getArticle(Model.articleId);
}

<h2>Editing Article: @Model.title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div>
        <div>
            @Html.HiddenFor(model => model.articleId, new { htmlAttributes = new { @class = "form-control", @Value = @article.articleid } })
        </div>
    </div>
    <div>
        <div >
            @Html.HiddenFor(model => model.workflow, new { htmlAttributes = new { @class = "form-control", @Value = @article.workflow_id } })
        </div>
    </div>
    <div>
        <div>
            @Html.HiddenFor(model => model.state, new { htmlAttributes = new { @class = "form-control", @Value = @article.state } })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.author, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.author, new { htmlAttributes = new { @class = "form-control", @Value = @article.author, @Disabled = true } })
            @Html.ValidationMessageFor(model => model.author, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control", @Value = article.article_title} })
            @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.body, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.body, new { htmlAttributes = new { @class = "form-control", @Value = article.article_text } })
            @Html.ValidationMessageFor(model => model.body, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.date_posted, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.date_posted, new { htmlAttributes = new { @class = "form-control", @Value = @article.date_posted, @Disabled = true } })
            @Html.ValidationMessageFor(model => model.date_posted, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Submit" class="btn btn-default" />
        </div>
    </div>

}

SocialMediaCenter/Views/Article/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

@{
    IEnumerable<Common.Article> allUserArticles = new LogicLayer.ArticleRepository().getUserArticles(User.Identity.Name);
    IEnumerable<Common.Article> allWriterUnreviewedArticles = new LogicLayer.ArticleRepository().getWriterUnreviewedArticles(User.Identity.Name);
    IEnumerable<Common.Article> allMMUnreviewedArticles = new LogicLayer.ArticleRepository().getMMUnreviewedArticles(User.Identity.Name);
    Common.User self = new LogicLayer.UserRepository().getUser(User.Identity.Name);
 }

<h2>Your Articles:</h2>

<h2>@self.Roles.FirstOrDefault().role_name </h2>

<table>
    <tr><td>Article Title</td> <td>Author</td> <td>Date Posted</td> <td> State </td> </tr>

    @{
        foreach (var a in allUserArticles)
        {
            Common.ArticleState s = new LogicLayer.ArticleRepository().getState(a.state);
            <tr><td>@a.article_title</td> <td>@a.author</td> <td>@a.date_posted</td> <td>@s.state_name</td> <td><a>@Html.ActionLink("Details", "Details", new { articleId = @a.articleid }, null)</a></td></tr>
        }
    }
</table>

@Html.ActionLink("New Article", "Create")

<h2>All Articles:</h2>

<table>
    <tr><td>Article Title</td> <td>Author</td> <td>Date Posted</td> </tr>

    @{
        if (new LogicLayer.UserRepository().getUserRole(User.Identity.Name).FirstOrDefault().roleid == 1)
        {
            foreach (var a in allWriterUnreviewedArticles)
            {
                <tr><td>@a.article_title</td> <td>@a.author</td> <td>@a.date_posted</td> <td>@Html.ActionLink("Review", "Review", new { articleId = @a.articleid }, null)</td></tr>
            }
        }

        else {
            foreach (var a in allMMUnreviewedArticles)
            {
                <tr><td>@a.article_title</td> <td>@a.author</td> <td>@a.date_posted</td> <td>@Html.ActionLink("Review", "Review", new { articleId = @a.articleid }, null)</td></tr>
            }
        }

    }
</table>

SocialMediaCenter/Views/Article/Review.cshtml
@model LogicLayer.Models.Model_ArticleReview

@{
    ViewBag.Title = "Review";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    Common.Article articleInReview = new LogicLayer.ArticleRepository().getArticle(Model.articleId);
}

<h2>Reviewing Article: @articleInReview.article_title </h2>

<p>
    @articleInReview.article_text
</p>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div>
        <div>
            @Html.HiddenFor(model => model.author, new { htmlAttributes = new { @class = "form-control", @Value = User.Identity.Name} })
        </div>
    </div>

<div class="form-group">
    @Html.LabelFor(model => model.comment, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.comment, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.comment, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.accepted, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.RadioButtonFor(model => model.accepted, "true") Accept
        @Html.RadioButtonFor(model => model.accepted, "false") Reject
    </div>
</div>

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Submit Review" class="btn btn-default" />
    </div>
</div>

}